### ISSUE TITLE
Get better sample names

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/sradownloader#1]
The SRA run selector kind of sucks for givng the correct names for samples.  The names on the metadata table seem to be taken from the BioSample record, which can have different names to GEO and the ones there are often worse.

There is a fairly easy way to look up the full details for a sample given the SRR number so we should do that if we can and fall back to the run selector data only if we need to (but give an option to use that directly).

For example in GSE126958 there is sample GSM4458675 which is called "oxWGBS_HUES64_WT_ESCs" but in the run selector it's just called "ESCs".

If we go to: https://www.ncbi.nlm.nih.gov/sra?term=SRX8077059&format=text we can get an easily parsed version of the file which we can take the title of to get the GSM, name, species  and sequence type which could all be useful.

**Comment by clydeugene** [comment]
Hi @s-andrews 

Thank you so much for developing this wonderful tool. I have used it quite a lot over the last year, and I am truly grateful for the work you put into it.

I wanted to bring to your attention an issue that I have noticed when downloading 10X single cell sequencing files for processing with cellranger. Cellranger expects the input files to be [named in a specific way](https://www.10xgenomics.com/support/software/cell-ranger/latest/analysis/inputs/cr-specifying-fastqs#file-naming-convention), but the file renaming strategy implemented in `sradownloader` does not account for this. 

Additionally, when there is an index file, the order of reads can get mixed up. Here's an example of files downloaded with the tool that include an index read:

```bash
$ ls -sh PRJNA597064/SRR10751502*
1.4G PRJNA597064/SRR10751502_GSM4228185_mIslets_I_A1_Mus_musculus_RNA-Seq_1.fastq.gz
5.3G PRJNA597064/SRR10751502_GSM4228185_mIslets_I_A1_Mus_musculus_RNA-Seq_2.fastq.gz
8.5G PRJNA597064/SRR10751502_GSM4228185_mIslets_I_A1_Mus_musculus_RNA-Seq_3.fastq.gz

```
Looking at the "Original format" table on [this SRA page](https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&acc=SRR10751502&display=data-access) it would appear that the smallest read (by file size) should be the index read, then the next size up would be read 1, with the largest file being read 2. However, that information is not reflected in the final names of the compressed fastq files.

> [!NOTE]
> For convenience I have pasted the "Original format" table for this sample below:
>
> |Type|Version|Created|Size|Location|Name|Free Egress|Access Type|
> |--- |--- |--- |--- |--- |--- |--- |--- |
> |fastq|1|2019-12-23|769.8MB|AWS|s3://sra-pub-src-6/SRR10751502/mIslets_I_A1_S3_L001_I1_001.fastq.gz.1|-|Use Cloud Data Delivery|
> |fastq|1|2019-12-23|4.5GB|AWS|s3://sra-pub-src-6/SRR10751502/mIslets_I_A1_S3_L001_R1_001.fastq.gz.1|-|Use Cloud Data Delivery|
> |fastq|1|2019-12-23|7.7GB|AWS|s3://sra-pub-src-6/SRR10751502/mIslets_I_A1_S3_L001_R2_001.fastq.gz.1|-|Use Cloud Data Delivery|

In the past I have dealt with this by writing a bash script that renames the files and to prepare them for Cellranger. However, I noticed that it is not always clear which file is the index, and in those moments my script would fail to name the files correctly, requiring manual overrides.

Would it be possible to parse the info in the table above to create better sample names that are Cellranger friendly?
