### ISSUE TITLE
Detect and remove 0-sized FastQ download files from ENA - and fall back to fasterq-dump

### ISSUE THREAD

**Issue by FelixKrueger** [s-andrews/sradownloader#10]
I heard from a 'colleague' that someone else encountered an issue, where `sradownloader` correctly retrieved filenames for some samples from GEO, and then tried to download the files from the ENA. All files were created, but they were all 0 byte-sized. The tool developer then asked my colleague, whether I could raise an issue on Github, so here it goes:

While this is clearly also an issue for the ENA (hosting 0-sized files is hardly ever useful), it might be a good idea for `sradownloader` to check for the file size of downloaded files, and if they are 0-sized, delete it and attempt to retrieve the file(s) from NCBI instead, using `fasterq-dump`.

Here is a test file you can use to elicit this behaviour. 
[SraRunTable.txt](https://github.com/s-andrews/sradownloader/files/5568640/SraRunTable.txt)

Running `sradownloader --noena SraRunTable.txt` seems to work just fine.

The code you are going to add for this issue will come in very handy for a pull request for MultiQC (so that it bows out more gracefully when it encounters 0-sized files from SNPsplit).

** Please don't ask me to contribute a pull-request for this, or if you do, please wait until next week. 

Thanks, Felix

**Comment by s-andrews** [comment]
Any chance you can give me a specific accession which fails.  That's a huge list and all of the ones I tried from it seemed to work OK.

**Comment by FelixKrueger** [comment]
Hmm, maybe they have fixed it by now? I don't think I have a specific one at hand right now, but I can try to add one next time I encounter the issue.

**Comment by s-andrews** [comment]
I've added a check for this.  We'll see if it works as expected if another example comes up.
