### ISSUE TITLE
Example data size difference

### ISSUE THREAD

**Issue by aryakaul** [s-andrews/sradownloader#14]
Hello!
Thanks for maintaining this tool! I was running through the example, and everything seemed to go correctly; however, when I check the filesizes I see a difference with what you have in the README?

```
.rw-rw-r-- 225M ak586 27 Mar 12:49 SRR5413015_GSM2563533_Spt3_5min_Saccharomyces_cerevisiae_ChIP-Seq_1.fastq.gz
.rw-rw-r-- 228M ak586 27 Mar 12:50 SRR5413015_GSM2563533_Spt3_5min_Saccharomyces_cerevisiae_ChIP-Seq_2.fastq.gz
.rw-rw-r-- 218M ak586 27 Mar 12:53 SRR5413016_GSM2563533_Spt3_5min_Saccharomyces_cerevisiae_ChIP-Seq_1.fastq.gz
.rw-rw-r-- 220M ak586 27 Mar 12:53 SRR5413016_GSM2563533_Spt3_5min_Saccharomyces_cerevisiae_ChIP-Seq_2.fastq.gz
```

Any idea what's behind this? The files look normal.

Thanks!
Arya

**Comment by s-andrews** [comment]
A couple of things:

1. The text on my original download is just wrong - the SRR5413015 sizes are way too small.  I must have grabbed the listing from an incomplete download whilst testing.  I'll fix that.

2. The sizes of the compressed files could potentially vary a bit depending on the compression level used.  From ENA we download gzipped data directly so those should be the same unless ENA re-compresses them (or compresses them on the fly), but from NCBI we do the compression locally which introduces a point of variance.  The uncompressed data should be the same though.

**Comment by aryakaul** [comment]
Thanks for the clarification!
