### ISSUE TITLE
Add explicit temp folder for fasterq-dump mode 

### ISSUE THREAD

**Issue by FelixKrueger** [s-andrews/sradownloader#17]
We recently had a run where a fairly large 10X sample caused global cluster issues by completely filling up the `/var/tmp/` partition.

The `fasterq-help` says:

```
-t|--temp <path>                 path to directory for temp. files
                                 (dflt=current dir.)
```

I somehow don't trust this though. Could we maybe specify the path to the tmp directory specifically, which I have found to work well with the offending sample?

e.g.

```
fasterq-dump -S -e 4 -m=10G -p --include-technical SRR11427630.sra -t `pwd`
```
  
Thanks!

**Comment by s-andrews** [comment]
Yeah, this makes sense to me.  Given that we're downloading into a folder which is going to expect large amounts of data then I actually don't see why we shouldn't just set the temp dir to the same as the download dir.
