### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by RichardCorbett** [s-andrews/sradownloader#18]
Hi there,
A teammate recommended I try using sradownloader.    This is my first attempt so I'm probably not doing something right.

I have `sra-tools` installed in a conda env. I have that env started when I run the command below.      

```
./sradownloader --outdir TEST_DOWNLOAD SraRunTable.txt
  File "./sradownloader", line 44
    print (f"[ENA] Downloading {sample['accession']} into {sample['file_base']}", flush=True)
                                                                               ^
SyntaxError: invalid syntax

```

Do you have any tips on how I can get around this?

thanks
Richard

**Comment by s-andrews** [comment]
Hi Richard.  I suspect you're probably just using an old version of python.   The syntax on that line uses a feature which was introduced in python 3.6, so you'll need something that new or newer to run it.

In your conda env can you try running ```python3 --version``` and see what you get.  If it's below 3.6 then you'll need to update to a newer version.

Let me know if you're still having problems after this.

**Comment by RichardCorbett** [comment]
Great.  You are correct about the python3 version:
```
python3 --version
Python 3.4.9
```

I'll update to python3.6 or higher and retest

**Comment by RichardCorbett** [comment]
Confirmed. Success with python 3.9!

**Comment by s-andrews** [comment]
Great.  Thanks for confirming.  I've updated the readme in [e9aa320](https://github.com/s-andrews/sradownloader/commit/e9aa320f4c376e13ab271f2bd548edb3130db993) to be more specific about the version of python required.
